// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jevzzasfjwrcekqghnic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impldnp6YXNmandyY2VrcWdobmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzkwNDcsImV4cCI6MjA3MjA1NTA0N30.CIJldRfN9RD251QrZZ1HV4F6kWo6jk22YVTC8vVlN-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});